// <auto-generated />
using Airbnb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airbnb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230325220823_multipletable")]
    partial class multipletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Airbnb.Models.Airbnb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("availability_365")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("host_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("host_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("latitude")
                        .HasColumnType("double");

                    b.Property<double>("longitude")
                        .HasColumnType("double");

                    b.Property<int>("minimum_nights")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("neighbourhood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("neighbourhood_group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("number_of_reviews")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("reviews")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("reviews_per_month")
                        .HasColumnType("double");

                    b.Property<string>("roomtype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airbnb");
                });

            modelBuilder.Entity("Airbnb.Models.Airbnb_review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("review")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Airbnb_review");
                });
#pragma warning restore 612, 618
        }
    }
}
